baseurl: ''
permalink: pretty
title: 'JooY.in'
headline-ml : "വ്യത്യസ്തമായ ഉത്പന്നങ്ങൾ ജോയിൽ മാത്രം "
headline-en : "JooY celebrates unique, creative, sustainable products."

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "80px"

home: 
  limit_services: 6 

collections:
  products:
    output: true
  categories:
    output: true

languages: ["en", "ml"]
default_lang: "en"
exclude_from_localization: ["_sass", "images", "assets", "public", "admin"]
lang_from_path: false
  

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ''          # An empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

sass:
  style: expanded # possible values: nested expanded compact compressed
  sourcemap: never
  line_comments: true

plugins:
  - jekyll-environment-variables
  - jekyll-polyglot

jekyll_admin:
  homepage: "posts"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md